name: soundfree
description: "A free Android music app."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  material_design_icons_flutter: ^7.0.7296
  url_launcher: ^6.3.2
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.3

flutter_native_splash:
  color: "#373737"
  image: assets/logo.png
  android_12:
    image: assets/logo.png
    color: "#373737"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png